### ISSUE TITLE
Height changing

### ISSUE THREAD

**Issue by madprops** [Recidvst/scrambling-letters#1]
Hi, nice library.

I was testing to see how it incorporated on my chat application. I wanted it to make a 500ms effect on chat messages.

It worked nicely (except that it sometimes didn't seem to do anything, maybe randomly picking the same letter all the time?), but there is a problem when the text is wide enough to jump between one or more lines in height, since the letters change, the text can overflow to another line for a bit. This height change is unwanted (so I had to revert it). Would be nice if there was a way so the text doesn't change height, even nicer if it doesn't change width too somehow. 

Thanks.

**Comment by Recidvst** [comment]
Hi madprops, 

Thanks for using the library :) Sorry to hear that you've had issues. 

Do you know what font you were using? I can't seem to replicate the issue locally myself but I can imagine the issue happening if using a font with particularly wide letters.

I'm not sure how to resolve this off the top of my head without messing with people's styling. I could shrink the text slightly while it scrambles or something similar but this was envisioned to be a JS library decoupled from the user's CSS and I would prefer to leave it this way. Open to suggestions if you have an idea though! 

In the short-term you might try a CSS fix for your use case. Slightly shrinking the text size while scrambling or forcing a maximum width might prevent the overflow issue?

I'm actually hoping to release a partial re-write of the library in the next few weeks so if I find a solution I will definitely include it then.

**Comment by madprops** [comment]
Thanks for the reply. This happens when the original text is near the right edge, so when letters change, the width changes naturally cause it to wrap to the next line for a bit. I think the solution would have to be CSS based, like setting a fixed width/height and using nowrap stuff, so I understand if you don't want to mess with that. I think a good alternative could be giving the element a temporary class like ".scrambling" or something so devs can do adjustments themselves, like preventing width/height changes, and then the class gets removed when the animation finishes. Not sure if a class is already being applied, I forgot to check.

Edit: Oh forgot to say, I'm using OpenSans

**Comment by Recidvst** [comment]
Yeah, I think that could be a good compromise. There is already a data attribute being toggled during the animation (`data-scramble-active`), but a class might be more accessible, so I'll look to add one with the next release and also add a note to the readme about font letter widths affecting the animation.

**Comment by Recidvst** [comment]
Closing this issue as the active class `scrambling` has now been added as part of release [1.5.0](https://github.com/Recidvst/scrambling-letters/releases/tag/v1.5.0). A warning/tip has also been added to the readme to explain the potential issue.
