### ISSUE TITLE
Random time not exact

### ISSUE THREAD

**Issue by madprops** [Recidvst/scrambling-letters#2]
I'm using random: [250, 250] to have exactly a 250ms animation.
But I'm finding it takes more than 250ms, like 500ms or more.

**Comment by Recidvst** [comment]
Hey @madprops, I've just pushed a fix for this issue. Found a flaw with the random time generator I think...! 
Please let me know if it solves your issue or not?

**Comment by madprops** [comment]
```
<script src='scramble.min.js'></script>

<div id='scrambleme'>This is a text to scramble</div>

<script>
    Scrambler({target:'#scrambleme', random:[250, 250], 
    beforeAll:function()
    {
        d1 = Date.now()
    }, afterAll:function()
    {
        d2 = Date.now()
        console.log(d2 - d1)
    }})

    setTimeout(function()
    {
        console.log('oiii')
    }, 250)
</script>
```

Running this test. The d2-d1 console log always show 401ms. But it looks alright, so I'm not sure, maybe the animation itself is 250ms.

When I tried implementing it myself I used something like:

`let delay = Math.min((args.duration - args.time), args.speed)`

Which takes into account the remaining time and speed to get the proper slice delay for the next timeout. Maybe that helps.

**Comment by Recidvst** [comment]
Ah, thanks for testing mate. I'll find some time to investigate this properly and review how it works. 👍
