### ISSUE TITLE
Function to execute upon completion

### ISSUE THREAD

**Issue by madprops** [Recidvst/scrambling-letters#3]
To circunvent jumping im doing this:

```
        let item = $(cls).get(0)
        item.style.height = `${item.clientHeight}px`

        Scrambler(
        {
            target: cls,
            random: [250, 250],
            speed: 100
        })

        setTimeout(function()
        {
            item.style.height = 'initial'
        }, 1000)
```

I have to use 1000ms because of the time not being exact issue I posted earlier.

A function that is called when the scrambling is done would help here. An optional function that is passed to Scrambler and executes it when animation finishes.

**Comment by Recidvst** [comment]
Thanks for this suggestion **madprops**. I've just pushed a new release (v1.6.0) which adds callback functions to the main Scrambler function:

`beforeEach`
`afterEach`
`beforeAll`
`afterAll`

The callback will return a reference to the element(s) in question as the first argument (optional) to allow you to target these.

**Comment by madprops** [comment]
Nice! very complete.
